version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: rspec-rails
    versions:
    - 4.0.2
    - 4.1.0
    - 5.0.0
  - dependency-name: rails
    versions:
    - 5.2.4.4
    - 5.2.4.5
  - dependency-name: bullet
    versions:
    - 6.1.3
  - dependency-name: loofah
    versions:
    - 2.9.0
  - dependency-name: grape-entity
    versions:
    - 0.8.2
  - dependency-name: webpacker
    versions:
    - 5.2.1
  - dependency-name: ffaker
    versions:
    - 2.17.0
