version: "3.8"
services:
  # redis:
  #   container_name: "key-value-store"
  #   image: "redis"
  #   ports:
  #     - "6379:6379"

  relational-db:
    container_name: "relational-db"
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${RDS_USERNAME}
      - POSTGRES_PASSWORD=${RDS_PASSWORD}
      - POSTGRES_DB=${RDS_DB_NAME}
    restart: always
    volumes:
      - relational-db-data:/var/lib/postgresql/data/
volumes:
  relational-db-data:
