version: "3.8"
services:
  # redis:
  #   container_name: "key-value-store"
  #   image: "redis"
  #   ports:
  #     - "6379:6379"

  relational-db:
    container_name: "relational-db"
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD", "pg_isready", "-U ${POSTGRES_USER}", "-d ${POSTGRES_DB}", "-p 5432"]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: always

  # volumes:
  #   - relational-db-data:/var/lib/postgresql/data/
