apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-rails-react-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
      - name: rails-app
        image: orbanbotond/rails-bikes:latest
        ports:
        - containerPort: 3000