@startuml
start

:Selects Rental Date Range;
:Filter by color/model/weight/rating;
:Reserve the Bike;

if (Cancels) then (yes)
  :The reservation is cancelled;
  :The bike is available for rent within the same dates;
else (no)
  :Rate the bike;
endif

stop
@enduml
